```{r}
EcophyCofog::Library(c("EcophyCofog","readr","dplyr","magrittr","ggplot2","patchwork","ggpubr","tidyr",'FactoMineR',"missMDA"))
```


# load data

```{r}
data_sat <- read.csv("../ressource/Site_edaphic_data/MappPtsSampled.csv") #site bioclim
load("../output/microeco_obj.Rdata") # metabar datasets
```


```{r}
data_sat %<>%
    mutate(Sample=ifelse(nchar(Sample)<3,paste0("0",Sample),Sample))%>%
    mutate(Sample=ifelse(nchar(Sample)<3,paste0("0",Sample),Sample))%>%
    mutate(Sample=ifelse(grepl("^8",Sample),paste0("0",Sample),Sample))%>% # fix 87a and 87b sample ids
    arrange(Sample)# fix sample ID to match the format of other MAPP datasets
```

# Mean on early month

Impute before mean? Or impute on mean? (missMDA)
```{r}
var <- colnames(data_sat)[grep('_lt', names(data_sat))] # extract long term variables (as they also exist on monthly basis)
months_we_want <- c("03","04","05")
data_sat %<>%
    mutate(across(.cols= colnames(data_sat),.fns = ~replace(., . ==  -9999 , NA)))%>%
    mutate(across(.cols=all_of(var),
                  ~get(paste0(gsub("_lt","_",cur_column()), months_we_want[1]))+
                       get(paste0(gsub("_lt","_",cur_column()), months_we_want[2]))+
                       get(paste0(gsub("_lt","_",cur_column()), months_we_want[3]))/3,
                  .names = "{col}_m3"
    ))
```



# Histograms covariates

```{r}
vars <- c("X","Y","bulk","gHM","height","ph","soc","water",colnames(mean_month_df)[grep('_lt', names(mean_month_df))])

for(i in vars){
  ggsave(plot=ggplot(mean_month_df,aes(x=mean_month_df[,i]))+
             geom_histogram(fill="darkolivegreen3")+
             theme_classic2()+
             xlab(i),filename=paste0("../Figures/cov_histogram/",i,".png"),height = 8,width = 8)
}
```


# Visualize correlation 

## correlation on long term
Subset some presumably important covariates

```{r}
var_cor <- GGally::ggpairs(
    data_sat %>% 
        select(c("X",
             "Y",
             "aet_lt",
             "bulk",
             "srad_lt",
             "def_lt",
             "evi_lt",
             "gHM",
             "gpp_lt",
             "height",
             'lai_lt',
             "moist_lt",
             "npp_lt",
             "pdsi_lt",
             "pet_lt",
             "ph",
             "pr_lt",
             "ssm_lt",
             "susm_lt",
             "swe_lt",
             "tmmn_lt",
             "tmmx_lt",
             "vap_lt",
             "vpd_lt",
             "fpar_lt",
             "soc",
             "water"))%>%
        mutate_all(.funs = ~replace(., . ==  -9999 , NA)),
    progress = T,
    cardinality_threshold = 105)
ggsave("../Figures/cov_cor.png",var_cor,height = 16,width = 16)
```

## Correlation on three months mean

```{r}
var_cor <- GGally::ggpairs(
    mean_month_df %>% 
        select(c("X",
             "Y",
             "aet_lt_m3",
             "bulk",
             "srad_lt_m3",
             "def_lt_m3",
             "evi_lt_m3",
             "gHM",
             "gpp_lt_m3",
             "height",
             'lai_lt_m3',
             "moist_lt_m3",
             "npp_lt_m3",
             "pdsi_lt_m3",
             "pet_lt_m3",
             "ph",
             "pr_lt_m3",
             "ssm_lt_m3",
             "susm_lt_m3",
             "swe_lt_m3",
             "tmmn_lt_m3",
             "tmmx_lt_m3",
             "vap_lt_m3",
             "vpd_lt_m3",
             "fpar_lt_m3",
             "soc",
             "water"))%>%
        mutate_all(.funs = ~replace(., . ==  -9999 , NA)),
    progress = T,
    cardinality_threshold = 105)
ggsave("../Figures/cov_cor_mean_3.png",var_cor,height = 16,width = 16)
```

# test missMDA imputing

## simple imputation
```{r}
nb <- estim_ncpPCA(data_sat %>% 
    select(c("X",
             "Y",
             "aet_lt",
             "bulk",
             "srad_lt",
             "def_lt",
             "evi_lt",
             "gHM",
             "gpp_lt",
             "height",
             'lai_lt',
             "moist_lt",
             "npp_lt",
             "pdsi_lt",
             "pet_lt",
             "ph",
             "pr_lt",
             "ssm_lt",
             "susm_lt",
             "swe_lt",
             "tmmn_lt",
             "tmmx_lt",
             "vap_lt",
             "vpd_lt",
             "fpar_lt",
             "soc",
             "water"
             ))%>%
        mutate(across(.fns = ~replace(., . ==  -9999 , NA))),scale=T)
imputed_data <- imputePCA(data_sat %>% 
    select(c("X",
             "Y",
             "aet_lt",
             "bulk",
             "srad_lt",
             "def_lt",
             "evi_lt",
             "gHM",
             "gpp_lt",
             "height",
             'lai_lt',
             "moist_lt",
             "npp_lt",
             "pdsi_lt",
             "pet_lt",
             "ph",
             "pr_lt",
             "ssm_lt",
             "susm_lt",
             "swe_lt",
             "tmmn_lt",
             "tmmx_lt",
             "vap_lt",
             "vpd_lt",
             "fpar_lt",
             "soc",
             "water"
             ))%>%
        mutate(across(.fns = ~replace(., . ==  -9999 , NA))),ncp=5,scale=T)
res.pca <- FactoMineR::PCA(imputed_data$completeObs)
```

## multiple imputation

```{r}
mi <- MIPCA(data_sat %>% 
    select(c("X",
             "Y",
             "aet_lt",
             "bulk",
             "srad_lt",
             "def_lt",
             "evi_lt",
             "gHM",
             "gpp_lt",
             "height",
             'lai_lt',
             "moist_lt",
             "npp_lt",
             "pdsi_lt",
             "pet_lt",
             "ph",
             "pr_lt",
             "ssm_lt",
             "susm_lt",
             "swe_lt",
             "tmmn_lt",
             "tmmx_lt",
             "vap_lt",
             "vpd_lt",
             "fpar_lt",
             "soc",
             "water"
             ))%>%
        mutate(across(.fns = ~replace(., . ==  -9999 , NA))),scale = T,ncp=5)
```


# PCA on sites

NA imputed as mean
```{r}
PCA_bioclim <- data_sat %>% 
    select(c("X",
             "Y",
             "aet_lt",
             "bulk",
             "srad_lt",
             "def_lt",
             "evi_lt",
             "gHM",
             "gpp_lt",
             "height",
             'lai_lt',
             "moist_lt",
             "npp_lt",
             "pdsi_lt",
             "pet_lt",
             "ph",
             "pr_lt",
             "ssm_lt",
             "susm_lt",
             "swe_lt",
             "tmmn_lt",
             "tmmx_lt",
             "vap_lt",
             "vpd_lt",
             "fpar_lt",
             "soc",
             "water"
             ))%>%
        mutate(across(.fns = ~replace(., . ==  -9999 , NA)))%>%
    FactoMineR::PCA(scale.unit = T,
                    graph = F)
```
```{r}
arrowMul <- function(arrows, data, at = c(0, 0), fill = 0.75) {
  u <- c(range(data[,1], range(data[,2])))
  u <- u - rep(at, each = 2)
  r <- c(range(arrows[, 1], na.rm = TRUE), range(arrows[, 2], na.rm = TRUE))
  rev <- sign(diff(u))[-2]
  if (rev[1] < 0)
    u[1:2] <- u[2:1]
  if (rev[2] < 0)
    u[3:4] <- u[4:3]
  u <- u/r
  u <- u[is.finite(u) & u > 0]
  fill * min(u)
}
```

```{r}
eig <- PCA_bioclim$eig
coord_pca <- as.data.frame(PCA_bioclim$ind$coord)
coord_pca$site <- data_sat$Sample
coord_pca$country <- data_sat$Country

mul <- arrowMul(as.data.frame(PCA_bioclim$var$coord),
               PCA_bioclim$ind$coord)

pca_site_biplot <- ggplot()+
    geom_point(coord_pca,mapping=aes(x=Dim.1,y=Dim.2),color="orange")+
    theme_classic2()+
    geom_vline(xintercept = 0,lty=2)+
    geom_hline(yintercept = 0,lty=2)+
    # ggrepel::geom_label_repel(data=filter(coord_pca,Dim.2< -3),aes(x=Dim.1,y=Dim.2,label=site))+
    xlab(paste0("PC1 (",round(eig[1,2],2),"%)"))+
    ylab(paste0("PC2 (",round(eig[2,2],2),"%)"))+
    geom_segment(data= as.data.frame(PCA_bioclim$var$coord),aes(x = 0, y = 0, xend=mul*Dim.1, yend=mul*Dim.2),
               lineend = "round", 
               linejoin = "round",
               linewidth = .75, 
               arrow = arrow(length = unit(0.2, "inches")),
               colour = "black" 
  )+
    ggrepel::geom_text_repel(data = data.frame(var=rownames(PCA_bioclim$var$coord),PCA_bioclim$var$coord*mul), # add variable names at the end of arrows
            aes(x = ifelse(Dim.1<0,Dim.1*1.1,Dim.1*1.1), # nudge a bit the coordinates so that they're not on the arrows
                y = ifelse(Dim.2<0,Dim.2*1.1,Dim.2*1.1),
                label = var),
             max.overlaps = getOption("ggrepel.max.overlaps", default = 15))+
    ggtitle("Biplot sites long term")+
    theme(plot.title = element_text(face="bold"))
ggsave(pca_site_biplot,filename="../Figures/PCA_sites.png")
    
```
